// <auto-generated />
using System;
using DinnerPlans.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DinnerPlans.Migrations
{
    [DbContext(typeof(DinnerPlansContext))]
    partial class DinnerPlansContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DinnerPlans.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NutritionDataId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("IngredientId");

                    b.HasIndex("NutritionDataId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DinnerPlans.Models.IngredientEntry", b =>
                {
                    b.Property<int>("IngredientEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("IngredientEntryId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientEntries");
                });

            modelBuilder.Entity("DinnerPlans.Models.NutritionData", b =>
                {
                    b.Property<int>("NutritionDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CarbsGr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FatsGr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProteinsGr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaltsGr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatFatsGr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SugarsGr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NutritionDataId");

                    b.ToTable("NutritionData");
                });

            modelBuilder.Entity("DinnerPlans.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NutritionDataId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId");

                    b.HasIndex("NutritionDataId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DinnerPlans.Models.Ingredient", b =>
                {
                    b.HasOne("DinnerPlans.Models.NutritionData", "NutritionData")
                        .WithMany()
                        .HasForeignKey("NutritionDataId");
                });

            modelBuilder.Entity("DinnerPlans.Models.IngredientEntry", b =>
                {
                    b.HasOne("DinnerPlans.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("DinnerPlans.Models.Recipe", null)
                        .WithMany("IngredientEntries")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("DinnerPlans.Models.Recipe", b =>
                {
                    b.HasOne("DinnerPlans.Models.NutritionData", "NutritionData")
                        .WithMany()
                        .HasForeignKey("NutritionDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
